project:
  type: website

website:
  title: "W06 Reflection Essay"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    number-sections: true
    code-link: true
    embed-resources: true